name: Update Homebrew Formula

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version
        required: true
      url_mac_arm64:
        description: URL for Mac ARM version
        required: true
      sha_mac_arm64:
        description: SHA256 for Mac ARM version
        required: true
      url_mac_x64:
        description: URL for Mac x64 version
        required: true
      sha_mac_x64:
        description: SHA256 for Mac x64 version
        required: true
      url_linux_x64:
        description: URL for Linux x64 version
        required: true
      sha_linux_x64:
        description: SHA256 for Linux x64 version
        required: true

jobs:
  update:
    name: Update & push Homebrew formula

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate formula
        id: generate-formula
        uses: actions/github-script@v6
        with:
          script: |
            const formula = `
            class Supersimple < Formula
              desc "CLI tool for Supersimple configuration management"
              homepage "https://github.com/gosupersimple/supersimple-cli"
              version "${{ github.event.inputs.version }}"

              on_macos do
                if Hardware::CPU.arm?
                  url "${{ github.event.inputs.url_mac_arm64 }}", :using => :nounzip
                  sha256 "${{ github.event.inputs.sha_mac_arm64 }}"

                  def install
                    bin.install "supersimple-arm64-apple-darwin" => "supersimple"
                  end
                else
                  url "${{ github.event.inputs.url_mac_x64 }}", :using => :nounzip
                  sha256 "${{ github.event.inputs.sha_mac_x64 }}"

                  def install
                    bin.install "supersimple-x86_64-apple-darwin" => "supersimple"
                  end
                end
              end

              on_linux do
                url "${{ github.event.inputs.url_linux_x64 }}", :using => :nounzip
                sha256 "${{ github.event.inputs.sha_linux_x64 }}"

                def install
                  bin.install "supersimple-x86_64-linux-gnu" => "supersimple"
                end
              end
            end
            `;

            return formula;

          result-encoding: string

      - name: Write formula to file
        run: echo '${{ steps.generate-formula.outputs.result }}' > Formula/supersimple.rb

      - name: Setup Git Config
        run: |
          git config --global user.name "Supersimple Bot"
          git config --global user.email "<>"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update Formula to ${{ github.event.inputs.version }}
          title: Update Formula to ${{ github.event.inputs.version }}
          body: |
            This PR updates the Homebrew Formula to version ${{ github.event.inputs.version }}.
          branch: update-formula-${{ github.event.inputs.version }}
          base: main
          reviewers: priithaamer
